analyze_cv:
  description: |
    Please deeply analyze the provided resume file and extract the following key information:
    
    **Analysis Dimensions:**
    1. **Professional Skills**: Programming languages, frameworks, tools, tech stack
    2. **Work Experience**: Position level, years of experience, project experience, management experience
    3. **Educational Background**: Degree, major, institution, relevant certifications
    4. **Core Strengths**: Areas of expertise, notable achievements, career highlights
    5. **Development Direction**: Career planning, skill preferences, industry tendencies
    
    **Output Requirements:**
    - Use structured format to organize information
    - Highlight key skills and experience highlights
    - Evaluate candidate's overall competitiveness
    - Identify potential career development directions
    
    **Resume File Path:** {cv_path}
    
  expected_output: |
    Structured resume analysis report containing:
    - Basic information summary
    - Skills matrix (categorized by proficiency level)
    - Work experience summary (highlighting key achievements)
    - Educational background
    - Core competency analysis
    - Career development recommendations

match_positions:
  description: |
    Based on the CV analysis results, find the best matching positions from the job database. Please conduct comprehensive matching analysis:
    
    **Matching Dimensions:**
    1. **Skill Match**:
       - Core skill coverage rate
       - Skill depth alignment
       - Tech stack compatibility
    
    2. **Experience Match**:
       - Years of experience required
       - Project experience relevance
       - Industry background alignment
    
    3. **Position Development Potential**:
       - Career progression ladder
       - Skill growth opportunities
       - Salary development expectations
    
    **Analysis Method:**
    - Calculate comprehensive match score for each position (0-100 points)
    - Analyze matching strengths and gaps
    - Provide specific matching rationale
    - Offer application advice and preparation directions
    
    **Job Data File:** {jobs_path}
    
  expected_output: |
    Job recommendation list sorted by match score:
    
    **Format Requirements:**
    Recommended Positions (Top 5)
    
    For each recommended position include:
    - Position Information: Job title, company, location, salary
    - Match Score: Total score + dimensional scores
    - Match Highlights: Core advantage analysis
    - Improvement Suggestions: Skills or experience enhancement directions
    - Application Strategy: Interview preparation focus points
    
    **Summary Section:**
    - Overall matching trend analysis
    - Career development path recommendations
    - Next steps action plan