export const senderMCPTools = [
  {
    id: '1008',
    name: 'Sequential Thinking',
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/sequential-thinking-mcp.png',
    brief_introduction: 'Facilitates step-by-step problem solving through a structured reasoning process.',
    details:
      'Facilitates step-by-step problem solving through a structured reasoning process. Reference: https://github.com/smithery-ai/reference-servers/tree/main/src/sequentialthinking\nConfiguration reference: https://smithery.ai/account/api-keys',
    need_config: false,
    config: {},
    ext: {
      name_en: 'Sequential Thinking',
      desc_en: 'Facilitates step-by-step problem resolution through structured reasoning processes.',
    },
  },
  {
    id: '1004',
    name: 'Gaode Maps',
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/amap.png',
    brief_introduction: 'Provides convenient access to 12 core geographic services, including route planning and location search.',
    details:
      'Supports geocoding, reverse geocoding, IP geolocation, weather queries, cycling, walking, driving and transit routes, distance calculation, keyword search, nearby search, and place details. Reference: https://lbs.amap.com/api/mcp-server/summary?spm=5176.28197581.d_mcp.2.21725a9eArhMtg\nConfiguration reference: https://lbs.amap.com/api/mcp-server/create-project-and-key',
    need_config: false,
    config: {},
    ext: {
      name_en: 'Gaode Map',
      desc_en:
        'Allows users to effortlessly access 12 core geographic services, such as route planning and location search.',
    },
  },
  {
    id: '1006',
    name: 'fetch-mcp',
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/fetch-mcp.png',
    brief_introduction: 'Enables large language models to fetch web content in HTML, JSON, plain text, and Markdown formats.',
    details:
      'Fetches web content in HTML, JSON, plain text, and Markdown formats.\nConfiguration reference: https://smithery.ai/account/api-keys',
    need_config: false,
    config: {},
    ext: {
      name_en: 'fetch-mcp',
      desc_en:
        'Empowers Large Language Models to fetch web content in various formats, including HTML, JSON, plain text, and Markdown.',
    },
  },
  {
    id: '2',
    name: 'Web Search',
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/web-search.png',
    brief_introduction: 'Searches the web for current information and returns results with titles, URLs, and snippets.',
    details: 'Searches the web for current information and returns results with titles, URLs, and snippets',
    need_config: false,
    config: {},
    ext: {
      name_en: 'Web Search',
      desc_en:
        'Performs web searches to retrieve the latest information relevant to queries, returning results with titles, URLs, and snippets.',
    },
  },
  {
    id: '1005',
    name: 'MySQL Database',
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/mysql-mcp.png',
    brief_introduction: 'Enables large language models to interact with MySQL databases through a standardized interface.',
    details:
      'This MCP server provides read-only access to MySQL databases. It can:\n- List available databases\n- List tables in a database\n- Describe table schemas\n- Execute read-only SQL queries',
    need_config: true,
    config: {
      user: 'USERNAME_EXAMPLE',
      password: 'PASSWORD_EXAMPLE',
      host: 'mysql.example.invalid',
      port: '3306',
      database: 'DATABASE_EXAMPLE',
    },
    ext: {
      name_en: 'MySQL Database',
      desc_en: 'Enables LLM to interact with MySQL databases through standardized interfaces.',
    },
  },
];

export const senderKnowledgeBases = [
  {
    instance_id: 'default',
    app_id: '9e2451a5',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Evaluation Criteria',
    knowledge_id: '6c949a28',
    visible_range: 2,
    org_ids: [],
    description: 'Evaluation criteria for the project',
    create_time: '2026-01-15 21:59:25',
    update_time: '2026-01-15 21:59:25',
    create_user: 'mxr_wanzhi',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: '37cf8a8b883942d9b8776dff5d71c8d3',
  },
  {
    instance_id: 'default',
    app_id: 'a6d6c43b',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Insurance Fundamentals',
    knowledge_id: 'f5a8c5ed',
    visible_range: 2,
    org_ids: [],
    description: 'Insurance Fundamentals',
    create_time: '2026-01-15 16:51:14',
    update_time: '2026-01-21 17:58:42',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: '1fcba685e3e84d42aa9722279f0a68c3',
  },
  {
    instance_id: 'default',
    app_id: 'a6d6c43b',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Life Insurance',
    knowledge_id: '4b949c37',
    visible_range: 2,
    org_ids: [],
    description: 'Lifetime Critical Illness Insurance Product Guide',
    create_time: '2026-01-14 15:19:41',
    update_time: '2026-01-14 15:19:41',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: '1fcba685e3e84d42aa9722279f0a68c3',
  },
  {
    instance_id: 'default',
    app_id: 'df757975',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Test Knowledge Base 0109 (2)',
    knowledge_id: 'aa0ef756',
    visible_range: 2,
    org_ids: [],
    description: 'Test',
    create_time: '2026-01-09 10:46:33',
    update_time: '2026-01-09 10:46:33',
    create_user: 'qiqiqi',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: '9ca998e1ee574392bba5bf67ec0b6d7f',
  },
  {
    instance_id: 'default',
    app_id: 'b7f5bd88',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Test Knowledge Base 0106',
    knowledge_id: '74c557be',
    visible_range: 2,
    org_ids: [],
    description: 'Private Knowledge Base 0106',
    create_time: '2026-01-06 12:47:35',
    update_time: '2026-01-06 18:38:16',
    create_user: 'fanyu0106',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: '5d1fd42119d04dac812bafb800c4ba2f',
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'fanyu1230',
    knowledge_id: '3ddd6a2b',
    visible_range: 2,
    org_ids: [],
    description: 'E-commerce Test 12348 v',
    create_time: '2025-12-30 10:42:15',
    update_time: '2026-01-06 19:30:34',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: '8f98b25c8c3946bdb540d94ef67f2115',
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'bug-fix',
    knowledge_id: '3fde7e75',
    visible_range: 2,
    org_ids: [],
    description: 'fix some files bug',
    create_time: '2025-12-26 16:19:22',
    update_time: '2026-01-06 17:17:53',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: 'a6d6c43b',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Insurance Demo',
    knowledge_id: '5beec68d',
    visible_range: 2,
    org_ids: [],
    description: 'Life Insurance',
    create_time: '2025-12-24 14:56:02',
    update_time: '2025-12-24 14:56:19',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'JSQ30-16T11(12T)U1 Product Manual',
    knowledge_id: '86334e6d',
    visible_range: 2,
    org_ids: [],
    description: 'JSQ30-16T11(12T)U1 Product Manual',
    create_time: '2025-12-15 15:48:59',
    update_time: '2025-12-15 15:48:59',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'HGY100-F376WU1 Manual',
    knowledge_id: '95b2a16f',
    visible_range: 2,
    org_ids: [],
    description: 'HGY100-F376WU1 Manual',
    create_time: '2025-12-15 15:32:23',
    update_time: '2025-12-15 15:32:23',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'CAP72GCA(81)U1 Indoor Unit Assembly',
    knowledge_id: '27087a8c',
    visible_range: 2,
    org_ids: [],
    description: 'CAP72GCA(81)U1 Indoor Unit Assembly',
    create_time: '2025-12-15 15:22:30',
    update_time: '2025-12-15 15:22:30',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'BCD-526WGHTD14S8U1 Manual',
    knowledge_id: '000f7b84',
    visible_range: 2,
    org_ids: [],
    description: 'BCD-526WGHTD14S8U1 Manual',
    create_time: '2025-12-15 15:14:28',
    update_time: '2025-12-15 15:14:28',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'BCD-451WDIYU1 Manual',
    knowledge_id: '570a4765',
    visible_range: 2,
    org_ids: [],
    description: 'BCD-451WDIYU1 Manual',
    create_time: '2025-12-15 14:29:30',
    update_time: '2025-12-15 14:29:30',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'G100298HBD14VTLSU1 Product Manual',
    knowledge_id: 'eed09020',
    visible_range: 2,
    org_ids: [],
    description: 'G100298HBD14VTLSU1 Product Manual',
    create_time: '2025-12-15 14:20:25',
    update_time: '2025-12-15 14:55:47',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Haier G100298HBD14VTLSU1 Manual Without PDF, Custom Images, Qwen 3 Model',
    knowledge_id: '02b524fe',
    visible_range: 2,
    org_ids: [],
    description: 'Haier G100298HBD14VTLSU1 Manual Without PDF, Custom Images, Qwen 3 Model',
    create_time: '2025-12-12 18:13:11',
    update_time: '2025-12-12 18:13:11',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Haier G100298HBD14VTLSU1 Manual Without PDF, Custom Images',
    knowledge_id: 'b1ed517e',
    visible_range: 2,
    org_ids: [],
    description: 'Haier G100298HBD14VTLSU1 Manual Without PDF, Custom Images',
    create_time: '2025-12-12 18:11:36',
    update_time: '2025-12-12 18:11:36',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Haier G100298HBD14VTLSU1 Manual Without PDF, Qwen 3 Model',
    knowledge_id: '96151e11',
    visible_range: 2,
    org_ids: [],
    description: 'Haier G100298HBD14VTLSU1 Manual Without PDF, Qwen 3 Model',
    create_time: '2025-12-12 18:10:37',
    update_time: '2025-12-12 18:10:37',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Haier G100298HBD14VTLSU1 Manual Without PDF',
    knowledge_id: '5d13fa63',
    visible_range: 2,
    org_ids: [],
    description: 'Haier G100298HBD14VTLSU1 Manual Without PDF',
    create_time: '2025-12-12 16:56:25',
    update_time: '2025-12-12 17:48:23',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Haier CAP72GCA(81)U1 Indoor Unit Assembly Manual',
    knowledge_id: '6cca0686',
    visible_range: 2,
    org_ids: [],
    description: 'Haier CAP72GCA(81)U1 Indoor Unit Assembly Manual',
    create_time: '2025-12-12 10:27:51',
    update_time: '2025-12-12 10:27:51',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Haier G100298HBD14VTLSU1 Manual',
    knowledge_id: '93946f5d',
    visible_range: 2,
    org_ids: [],
    description: 'Haier G100298HBD14VTLSU1 Manual',
    create_time: '2025-12-12 10:24:32',
    update_time: '2025-12-12 10:24:32',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Haier Demo 3',
    knowledge_id: '814ee687',
    visible_range: 2,
    org_ids: [],
    description: 'BCD-526WGHTD14S8U1.pdf',
    create_time: '2025-12-11 18:37:03',
    update_time: '2025-12-11 18:37:03',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '7c7e56a4',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: '122',
    knowledge_id: '0c1e7baf',
    visible_range: 2,
    org_ids: [],
    description: '123',
    create_time: '2025-12-10 19:38:28',
    update_time: '2025-12-10 19:38:28',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Haier Demo 2',
    knowledge_id: '2f86cc05',
    visible_range: 2,
    org_ids: [],
    description: 'JSQ30-16T11(12T)U1 Product Manual.pdf',
    create_time: '2025-12-10 17:27:41',
    update_time: '2025-12-11 18:36:02',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '85e54bc7',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Test Knowledge Base - Public',
    knowledge_id: 'fad801a9',
    visible_range: 2,
    org_ids: [],
    description: '',
    create_time: '2025-12-08 15:59:19',
    update_time: '2025-12-08 15:59:19',
    create_user: 'testAccount3',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Haier Demo',
    knowledge_id: '06672e3a',
    visible_range: 2,
    org_ids: [],
    description: 'HGY100-F376WU1 Manual.pdf',
    create_time: '2025-12-08 11:36:17',
    update_time: '2025-12-11 18:36:35',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '9cc9f719',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'test123',
    knowledge_id: '75516c0e',
    visible_range: 2,
    org_ids: [],
    description: 'test',
    create_time: '2025-12-03 17:08:12',
    update_time: '2025-12-05 11:09:44',
    create_user: 'root',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '71c56c3e',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Example Knowledge Base',
    knowledge_id: 'c896533d',
    visible_range: 2,
    org_ids: [],
    description: 'Example City Guide',
    create_time: '2025-12-02 18:56:14',
    update_time: '2025-12-02 18:56:14',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '71c56c3e',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Example City IP',
    knowledge_id: '4a600d6f',
    visible_range: 2,
    org_ids: [],
    description: 'Example City IP and Digital Human',
    create_time: '2025-12-01 16:12:49',
    update_time: '2025-12-01 16:12:49',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '0d4a9f79',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'DigitalManTest',
    knowledge_id: '41b9382f',
    visible_range: 2,
    org_ids: [],
    description: 'Digital Human Test',
    create_time: '2025-12-01 15:55:55',
    update_time: '2025-12-01 15:55:55',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '510ba961',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: '112',
    knowledge_id: 'ca6afe9b',
    visible_range: 3,
    org_ids: [],
    description: '111',
    create_time: '2025-11-30 09:09:08',
    update_time: '2025-11-30 09:09:08',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '36e19a34',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'AI Assistant',
    knowledge_id: '1adfe166',
    visible_range: 2,
    org_ids: [],
    description: '',
    create_time: '2025-11-28 17:58:53',
    update_time: '2025-11-28 17:58:53',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: true,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'ADMIN',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: 'a918973b',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Test Knowledge Base 2',
    knowledge_id: 'a292ccc2',
    visible_range: 2,
    org_ids: [],
    description: '',
    create_time: '2025-11-27 23:50:12',
    update_time: '2025-11-27 23:50:12',
    create_user: 'fanyu11',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: 'a918973b',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: 'Knowledge Base Test',
    knowledge_id: '027ef204',
    visible_range: 2,
    org_ids: [],
    description: 'Test',
    create_time: '2025-11-27 23:33:38',
    update_time: '2025-11-27 23:33:38',
    create_user: 'fanyu11',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: false,
    knowledge_type: null,
    embed_type: 'qwen3-8B',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'READER',
    member_cnt: null,
    user_id: null,
  },
  {
    instance_id: 'default',
    app_id: '36e19a34',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: '1',
    knowledge_id: '88839bc0',
    visible_range: 1,
    org_ids: [],
    description: '',
    create_time: '2025-10-09 16:22:09',
    update_time: '2025-10-09 16:22:09',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: true,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'ADMIN',
    member_cnt: null,
    user_id: null,
  },
];

export const senderSandboxTools = [
  {
    id: 24,
    agent_tool_id: 'cloud_phone',
    tool_type: 'SANDBOX',
    tool_name: 'Virtual Phone',
    status: 'ACTIVE',
    avatar: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/phone.png',
    desc: 'A high-performance cloud phone environment for running mobile applications without physical devices.',
    location: '/console/workshop/popai/sandbox-agent',
    tool_name_en: 'Cloud Phone',
    desc_en:
      'A cloud-based high-performance virtual mobile environment, breaking physical device limitations to run various APPs.',
  },
  {
    id: 29,
    agent_tool_id: 'phone_rpa_tool',
    tool_type: 'SANDBOX',
    tool_name: 'RPA Phone',
    status: 'ACTIVE',
    avatar: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/phone.png',
    desc: 'Automates a virtual phone to run RPA tasks.',
    location: '/console/workshop/popai/sandbox-agent',
    tool_name_en: 'RPA Phone',
    desc_en:
      'Automate virtual phone operations to execute RPA automation tasks.',
  },
  {
    id: 25,
    agent_tool_id: 'code_interceptor',
    tool_type: 'SANDBOX',
    tool_name: 'Code Interpreter',
    status: 'ACTIVE',
    avatar: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/code.png',
    desc: 'An isolated environment for executing code safely and efficiently.',
    tool_name_en: 'Code Interpreter',
    desc_en: 'Lightning-fast and secure web browsing, aggregating real-time information across the internet.',
  },
  {
    id: 26,
    agent_tool_id: 'browser',
    tool_type: 'SANDBOX',
    tool_name: 'Browser',
    status: 'ACTIVE',
    avatar: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/browser.png',
    desc: 'Browses the web safely and retrieves current information.',
    desc_en: 'Lightning-fast and secure web browsing, aggregating real-time information across the internet.',
    tool_name_en: 'Browser',
  },
  {
    id: 27,
    agent_tool_id: 'terminal',
    tool_type: 'SANDBOX',
    tool_name: 'Virtual Terminal',
    status: 'ACTIVE',
    avatar: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/terminal.png',
    desc: 'A lightweight Linux virtual machine for running commands and programs.',
    desc_en: 'A lean yet powerful Linux VM supporting command execution and program operations.',
    tool_name_en: 'Virtual Terminal',
  },
  {
    id: 28,
    agent_tool_id: 'content_security',
    tool_type: 'SANDBOX',
    tool_name: 'Content Safety Guardrails',
    status: 'ACTIVE',
    avatar: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/%E5%86%85%E5%AE%B9%E5%AE%89%E5%85%A8%E6%8A%A4%E6%A0%8F.png',
    desc: 'Checks user input and model output against generative AI service safety requirements.',
    tool_name_en: 'Content Safety Filter',
    desc_en:
      'Scans user inputs and AI-generated outputs for compliance with <Basic Security Requirements for Generative AI Services> .',
  },
  {
    id: 54,
    agent_tool_id: 'cloud_pc',
    tool_type: 'SANDBOX',
    tool_name: 'Virtual Desktop',
    status: 'COMING',
    avatar: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/pc.png',
    desc: 'Runs desktop applications for a variety of workflows.',
    tool_name_en: 'Virtual Desktop',
    desc_en: 'Operate diverse PC software ecosystems to meet multifaceted work requirements.',
  },
];

export const knowledgeBases = [
  {
    instance_id: 'default',
    app_id: '36e19a34',
    instance_name: 'default',
    instance_host: 'default',
    index_name: 'default',
    name: '1',
    knowledge_id: '88839bc0',
    description: '',
    create_time: '2025-10-09 16:22:09',
    update_time: '2025-10-09 16:22:09',
    create_user: 'Example User',
    doc_cnt: null,
    task_cnt: null,
    is_public: false,
    is_editable: true,
    knowledge_type: null,
    embed_type: 'bge-m3',
    category: 'normal',
    sync_period: null,
    sync_next_time: null,
    role: 'OWNER',
    member_cnt: null,
  },
];

export const mcpTools = [
  {
    agent_tool_id: 'gaode_map',
    id: 1,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/amap.png',
    name: 'Gaode Maps',
    desc: 'Provides convenient access to 12 core geographic services, including route planning and location search.',
    type: 'MCP',
    service_type: 'sse',
    status: 'ACTIVE',
    need_config: false,
    content: {
      mcpServers: {
        'amap-amap-sse': {
          url: 'https://mcp.amap.com/sse?key=${token}',
          transport: 'sse',
        },
      },
    },
    config: null,
    ext: {
      name_en: 'Gaode Map',
      desc_en:
        'Allows users to effortlessly access 12 core geographic services, such as route planning and location search.',
    },
    credentials: null,
    create_time: '2025-09-08 09:11:27',
    update_time: '2025-09-08 09:11:27',
    config_list: null,
  },
  {
    agent_tool_id: 'fetch_mcp',
    id: 2,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/fetch-mcp.png',
    name: 'Fetch MCP',
    desc: 'Enables large language models to fetch web content in Markdown format.',
    type: 'MCP',
    service_type: 'streamable_http',
    status: 'ACTIVE',
    need_config: false,
    content: {
      mcpServers: {
        'fetch-mcp': {
          url: 'http://localhost:8888/api/v1/mcp-fetch/mcp',
        },
      },
    },
    config: null,
    ext: {
      name_en: 'fetch-mcp',
      desc_en:
        'Empowers Large Language Models to fetch web content in various formats, including HTML, JSON, plain text, and Markdown.',
    },
    credentials: null,
    create_time: '2025-09-08 09:11:27',
    update_time: '2025-09-08 09:11:27',
    config_list: null,
  },
  {
    agent_tool_id: 'web_search',
    id: 3,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/web-search.png',
    name: 'Web Search',
    desc: 'Searches the web for current information and returns results with titles, URLs, and snippets.',
    type: 'MCP',
    service_type: 'streamable_http',
    status: 'ACTIVE',
    need_config: false,
    content: {
      mcpServers: {
        'wanzhi-web-search': {
          url: 'http://localhost:8888/api/v1/mcp-web-search/mcp',
        },
      },
    },
    config: null,
    ext: {
      name_en: 'Web Search',
      desc_en:
        'Performs web searches to retrieve the latest information relevant to queries, returning results with titles, URLs, and snippets.',
    },
    credentials: null,
    create_time: '2025-09-08 09:11:27',
    update_time: '2025-09-08 09:11:27',
    config_list: null,
  },
  {
    agent_tool_id: 'mysql_database',
    id: 4,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/mysql-mcp.png',
    name: 'MySQL Database',
    desc: 'Enables large language models to interact with MySQL databases through a standardized interface.',
    type: 'MCP',
    service_type: 'streamable_http',
    status: 'ACTIVE',
    need_config: true,
    content: {
      mcpServers: {
        mysql: {
          url: 'http://localhost:8888/api/v1/mcp-mysql/mcp?user=${user}&password=${password}&host=${host}&port=${port}&database=${database}',
        },
      },
    },
    config: [
      {
        param_name: 'user',
        param_value: null,
        is_optional: false,
      },
      {
        param_name: 'password',
        param_value: null,
        is_optional: false,
      },
      {
        param_name: 'host',
        param_value: null,
        is_optional: false,
      },
      {
        param_name: 'port',
        param_value: null,
        is_optional: false,
      },
      {
        param_name: 'database',
        param_value: null,
        is_optional: false,
      },
    ],
    ext: {
      name_en: 'MySQL Database',
      desc_en: 'Enables LLM to interact with MySQL databases through standardized interfaces.',
      param_config: [
        {
          param_name: 'user',
          is_optional: false,
        },
        {
          param_name: 'password',
          is_optional: false,
        },
        {
          param_name: 'host',
          is_optional: false,
        },
        {
          param_name: 'port',
          is_optional: false,
        },
        {
          param_name: 'database',
          is_optional: false,
        },
      ],
    },
    credentials: null,
    create_time: '2025-09-08 09:11:27',
    update_time: '2025-09-08 09:11:27',
    config_list: null,
  },
  {
    agent_tool_id: 'mcp_server_chart',
    id: 6,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/chart-mcp.png',
    name: 'Data Visualization',
    desc: 'A Chart MCP server for data visualization and chart generation.',
    type: 'MCP',
    service_type: 'sse',
    status: 'ACTIVE',
    need_config: false,
    content: {
      mcpServers: {
        'mcp-server-chart': {
          type: 'sse',
          url: 'https://mcp.example.invalid/chart/sse',
        },
      },
    },
    config: null,
    ext: {
      name_en: 'Chart MCP Server',
      desc_en: 'Provides data visualization and chart generation capabilities.',
    },
    credentials: null,
    create_time: null,
    update_time: null,
    config_list: null,
  },
  {
    agent_tool_id: 'digitalman',
    id: 108,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/digital_human.png',
    name: 'Digital Human',
    desc: 'Converts agent-generated content into a narrated digital-human video.',
    type: 'MCP',
    service_type: 'sse',
    status: 'ACTIVE',
    need_config: false,
    content: {
      mcpServers: {
        digital_human: {
          url: 'https://demo2-digitalhuman-api.lingyiwanwu.com/mcp-video-gen/sse',
          transport: 'sse',
        },
      },
    },
    config: null,
    ext: {
      name_en: 'Digital Human',
      desc_en: 'Converts content generated by the Agent into digital human explanation videos.',
    },
    credentials: null,
    create_time: '2025-09-24 16:58:41',
    update_time: '2025-09-24 16:58:41',
    config_list: null,
  },
  {
    agent_tool_id: 'qichacha',
    id: 111,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/qichacha-mcp.png',
    name: 'Company Information Search',
    desc: 'A company-information service for registration data, fuzzy search, and risk checks.',
    type: 'MCP',
    service_type: 'streamable_http',
    status: 'ACTIVE',
    need_config: false,
    content: {
      mcpServers: {
        qichacha: {
          url: 'http://localhost:8888/api/v1/mcp-qichacha/mcp',
        },
      },
    },
    config: null,
    ext: {
      name_en: 'Qichacha',
      desc_en: 'Provides enterprise business registration information, fuzzy search, and risk investigation features.',
    },
    credentials: null,
    create_time: '2025-09-25 14:35:52',
    update_time: '2025-09-25 14:35:52',
    config_list: null,
  },
  {
    agent_tool_id: '12306',
    id: 113,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/12306-mcp.png',
    name: '12306 Railway Search',
    desc: 'A 12306 MCP server for railway schedule searches and ticket-booking workflows.',
    type: 'MCP',
    service_type: 'streamable_http',
    status: 'ACTIVE',
    need_config: false,
    content: {
      mcpServers: {
        '12306': {
          type: 'streamable_http',
          url: 'https://mcp.example.invalid/railway/mcp',
        },
      },
    },
    config: null,
    ext: {
      name_en: '12306 Railway',
      desc_en: 'Enables access to China Railway Customer Service Center for ticketing and schedule queries.',
    },
    credentials: null,
    create_time: '2025-09-25 15:06:22',
    update_time: '2025-09-25 15:06:22',
    config_list: null,
  },
  {
    agent_tool_id: 'MiniMax',
    id: 114,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/MiniMax.png',
    name: 'MiniMax',
    desc: 'Minimax MCP provides multimodal generation for audio, music, images, and video.',
    type: 'MCP',
    service_type: 'streamable_http',
    status: 'ACTIVE',
    need_config: false,
    content: {
      mcpServers: {
        'MiniMax-MCP': {
          url: 'https://mcp.example.invalid/minimax/mcp',
        },
      },
    },
    config: null,
    ext: {
      name_en: 'MiniMax',
      desc_en: 'Provides powerful multimodal generation capabilities across audio, music, image, and video domains.',
    },
    credentials: null,
    create_time: '2025-09-25 15:16:38',
    update_time: '2025-09-25 15:16:38',
    config_list: null,
  },
  {
    agent_tool_id: 'feishu',
    id: 115,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/lark-mcp.png',
    name: 'Feishu',
    desc: 'A Feishu MCP server that integrates with the Feishu platform.',
    type: 'MCP',
    service_type: 'stdio',
    status: 'ACTIVE',
    need_config: true,
    content: {
      mcpServers: {
        'lark-mcp': {
          command: 'npx',
          args: [
            '-y',
            '@larksuiteoapi/lark-mcp',
            'mcp',
            '-a',
            '${your_app_id}',
            '-s',
            '${your_app_secret}',
            '-u',
            '${your_user_token}',
          ],
          transport: 'stdio',
        },
      },
    },
    config: [
      {
        param_name: 'your_app_id',
        param_value: null,
        is_optional: true,
      },
      {
        param_name: 'your_app_secret',
        param_value: null,
        is_optional: true,
      },
      {
        param_name: 'your_user_token',
        param_value: null,
        is_optional: true,
      },
    ],
    ext: {
      name_en: 'Feishu',
      desc_en: 'Offers integration capabilities with the Feishu (Lark) collaboration platform.',
    },
    credentials: null,
    create_time: '2025-09-25 15:22:13',
    update_time: '2025-09-25 15:22:13',
    config_list: null,
  },
  {
    agent_tool_id: 'postgresql_database',
    id: 123,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/mcp_server_icon/postgresql-mcp.png',
    name: 'PostgreSQL Database',
    desc: 'Enables large language models to interact with PostgreSQL databases through a standardized interface.',
    type: 'MCP',
    service_type: 'streamable_http',
    status: 'ACTIVE',
    need_config: true,
    content: {
      mcpServers: {
        postgresql: {
          url: 'http://localhost:8888/api/v1/mcp-postgresql/mcp?user=${user}&password=${password}&host=${host}&port=${port}&database=${database}',
        },
      },
    },
    config: [
      {
        param_name: 'user',
        param_value: null,
        is_optional: false,
      },
      {
        param_name: 'password',
        param_value: null,
        is_optional: false,
      },
      {
        param_name: 'host',
        param_value: null,
        is_optional: false,
      },
      {
        param_name: 'port',
        param_value: null,
        is_optional: false,
      },
      {
        param_name: 'database',
        param_value: null,
        is_optional: false,
      },
    ],
    ext: {
      name_en: 'PostgreSQL Database',
      desc_en: 'Enables LLM to interact with PostgreSQL databases through standardized interfaces.',
      param_config: [
        {
          param_name: 'user',
          is_optional: false,
        },
        {
          param_name: 'password',
          is_optional: false,
        },
        {
          param_name: 'host',
          is_optional: false,
        },
        {
          param_name: 'port',
          is_optional: false,
        },
        {
          param_name: 'database',
          is_optional: false,
        },
      ],
    },
    credentials: null,
    create_time: '2025-09-29 15:48:54',
    update_time: '2025-09-29 15:48:54',
    config_list: null,
  },
  {
    agent_tool_id: 'f3451d9f4bb242ec',
    id: 136,
    icon: '/static/image/my-agent-default-avatar.b998d96f.png',
    name: 'Feishu Recruiting',
    desc: 'Feishu Recruiting',
    type: 'MCP',
    service_type: 'streamable_http',
    status: 'ACTIVE',
    need_config: false,
    content: {
      mcpServers: {
        'feishu-mcp': {
          url: 'http://localhost:8888/api/v1/mcp-feishu-recruitment/mcp',
        },
      },
    },
    config: null,
    ext: {
      name_en: 'Feishu Recruiting',
    },
    credentials: null,
    create_time: '2025-10-28 10:52:35',
    update_time: '2025-10-28 10:52:35',
    config_list: null,
  },
  {
    agent_tool_id: 'keling_video',
    id: 138,
    icon: '/static/image/my-agent-default-avatar.b998d96f.png',
    name: 'Video Generation',
    desc: 'Enduring Promise',
    type: 'MCP',
    service_type: 'streamable_http',
    status: 'ACTIVE',
    need_config: true,
    content: {
      mcpServers: {
        keling_video: {
          url: 'http://localhost:8888/api/v1/mcp-keling-video/mcp?access_key=${access_key}&secret_key=${secret_key}',
        },
      },
    },
    config: [
      {
        param_name: 'access_key',
        param_value: 'ACCESS_KEY_EXAMPLE',
        is_optional: true,
      },
      {
        param_name: 'secret_key',
        param_value: 'SECRET_KEY_EXAMPLE',
        is_optional: true,
      },
    ],
    ext: {
      name_en: 'Video Generation',
    },
    credentials: null,
    create_time: null,
    update_time: null,
    config_list: null,
  },
];

export const pluginTools = [
  {
    agent_tool_id: 'seekerliu/bocha/bocha',
    id: null,
    icon: 'https://test-app.lingyiwanwu.net/gateway/dify/api/console/api/workspaces/current/plugin/icon?tenant_id=16fac2b3-7374-4ec4-9183-0f2dff90e35b&filename=6fc9b088775e6989b928672f2d8aeb764bdfd017127d04ed71fea55089c5aa74.svg',
    name: 'seekerliu/bocha/bocha',
    desc: 'Bocha is an AI search engine that retrieves high-quality information from billions of web pages and content sources, including weather, news, encyclopedias, healthcare, railway tickets, and images.',
    type: 'builtin',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: null,
    config: null,
    ext: {
      desc_en:
        'Bocha is a Chinese search engine for AI, you can get enhanced search details from billions of web documents, including weather, news, wikis, healthcare, train tickets, images, and more.',
      name_en: 'seekerliu/bocha/bocha',
    },
    credentials: null,
    create_time: null,
    update_time: null,
    config_list: null,
  },
  {
    agent_tool_id: 'langgenius/wikipedia/wikipedia',
    id: null,
    icon: 'https://test-app.lingyiwanwu.net/gateway/dify/api/console/api/workspaces/current/plugin/icon?tenant_id=16fac2b3-7374-4ec4-9183-0f2dff90e35b&filename=a83ac9eac258f6710e51050e914e9b97d978fcbfc2b53923f4f320c8eef44424.svg',
    name: 'langgenius/wikipedia/wikipedia',
    desc: 'Wikipedia is a free online encyclopedia created and edited by volunteers around the world.',
    type: 'builtin',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: null,
    config: null,
    ext: {
      desc_en: 'Wikipedia is a free online encyclopedia, created and edited by volunteers around the world.',
      name_en: 'langgenius/wikipedia/wikipedia',
    },
    credentials: null,
    create_time: null,
    update_time: null,
    config_list: null,
  },
];

export const sandboxTools = [
  {
    agent_tool_id: 'phone_rpa_tool',
    id: 29,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/phone.png',
    name: 'RPA Phone',
    desc: 'Automates a virtual phone to run RPA tasks.',
    type: 'SANDBOX',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {},
    config: null,
    ext: {
      name_en: 'RPA Phone',
      desc_en: 'Automate virtual phone operations to execute RPA automation tasks.',
    },
    credentials: null,
    create_time: '2025-09-08 09:04:47',
    update_time: '2025-09-08 09:04:47',
    config_list: null,
  },
  {
    agent_tool_id: 'code_interceptor',
    id: 25,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/code.png',
    name: 'Code Interpreter',
    desc: 'An isolated environment for executing code safely and efficiently.',
    type: 'SANDBOX',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {},
    config: null,
    ext: {
      name_en: 'Code Interpreter',
      desc_en: 'Lightning-fast and secure web browsing, aggregating real-time information across the internet.',
    },
    credentials: null,
    create_time: '2025-09-08 09:04:47',
    update_time: '2025-09-08 09:04:47',
    config_list: null,
  },
  {
    agent_tool_id: 'browser',
    id: 26,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/browser.png',
    name: 'Browser',
    desc: 'Browses the web safely and retrieves current information.',
    type: 'SANDBOX',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {},
    config: null,
    ext: {
      name_en: 'Browser',
      desc_en: 'Lightning-fast and secure web browsing, aggregating real-time information across the internet.',
    },
    credentials: null,
    create_time: '2025-09-08 09:04:47',
    update_time: '2025-09-08 09:04:47',
    config_list: null,
  },
  {
    agent_tool_id: 'terminal',
    id: 27,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/terminal.png',
    name: 'Virtual Terminal',
    desc: 'A lightweight Linux virtual machine for running commands and programs.',
    type: 'SANDBOX',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {},
    config: null,
    ext: {
      name_en: 'Virtual Terminal',
      desc_en: 'A lean yet powerful Linux VM supporting command execution and program operations.',
    },
    credentials: null,
    create_time: '2025-09-08 09:04:47',
    update_time: '2025-09-08 09:04:47',
    config_list: null,
  },
  {
    agent_tool_id: 'content_security',
    id: 28,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/%E5%86%85%E5%AE%B9%E5%AE%89%E5%85%A8%E6%8A%A4%E6%A0%8F.png',
    name: 'Content Safety Guardrails',
    desc: 'Checks user input and model output against generative AI service safety requirements.',
    type: 'SANDBOX',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {},
    config: null,
    ext: {
      name_en: 'Content Safety Filter',
      desc_en:
        'Scans user inputs and AI-generated outputs for compliance with <Basic Security Requirements for Generative AI Services> .',
    },
    credentials: null,
    create_time: '2025-09-08 09:04:47',
    update_time: '2025-09-08 09:04:47',
    config_list: null,
  },
  {
    agent_tool_id: 'cloud_phone',
    id: 53,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/phone.png',
    name: 'Virtual Phone',
    desc: 'A high-performance cloud phone environment for running mobile applications without physical devices.',
    type: 'SANDBOX',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {},
    config: null,
    ext: {
      name_en: 'Cloud Phone',
      desc_en:
        'A cloud-based high-performance virtual mobile environment, breaking physical device limitations to run various APPs.',
    },
    credentials: null,
    create_time: '2025-09-08 09:04:47',
    update_time: '2025-09-08 09:04:47',
    config_list: null,
  },
  {
    agent_tool_id: 'cloud_pc',
    id: 54,
    icon: 'https://productivity-console-prod-sh.oss-cn-shanghai.aliyuncs.com/agent_box/pc.png',
    name: 'Virtual Desktop',
    desc: 'Runs desktop applications for a variety of workflows.',
    type: 'SANDBOX',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {},
    config: null,
    ext: {
      name_en: 'Virtual Desktop',
      desc_en: 'Operate diverse PC software ecosystems to meet multifaceted work requirements.',
    },
    credentials: null,
    create_time: '2025-09-08 09:04:47',
    update_time: '2025-09-08 09:04:47',
    config_list: null,
  },
];

export const skillTools = [
  {
    agent_tool_id: 'document_skills_pptx',
    id: 141,
    icon: '/static/image/my-agent-default-avatar.b998d96f.png',
    name: 'PPTX Creation Tool',
    desc: 'An AI-powered presentation tool for creating, editing, and analyzing slide decks.',
    type: 'skills',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {
      tool_name: 'document_skills_pptx',
      tool_description:
        'Presentation creation, editing, and analysis. This tool works with presentation files (.pptx files) for: (1) Creating new presentations, (2) Modifying or editing content, (3) Working with layouts, (4) Adding comments or speaker notes, or any other presentation tasks',
    },
    config: null,
    ext: {
      name_en: 'PPTX Skill',
      desc_en: 'AI-powered professional PowerPoint creation tool for presentations',
    },
    credentials: null,
    create_time: '2025-11-05 23:27:23',
    update_time: '2025-11-05 23:27:23',
    config_list: null,
  },
  {
    agent_tool_id: 'document_skills_docx',
    id: 142,
    icon: '/static/image/my-agent-default-avatar.b998d96f.png',
    name: 'Word Document Tool',
    desc: 'An AI-powered Word tool for creating, editing, and formatting documents.',
    type: 'skills',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {
      tool_name: 'document_skills_docx',
      tool_description:
        'Document creation, editing, and analysis with support for tracked changes, comments, formatting preservation, and text extraction. This tool works with professional documents (.docx files) for: (1) Creating new documents, (2) Modifying or editing content, (3) Working with tracked changes, (4) Adding comments, or any other document tasks',
    },
    config: null,
    ext: {
      name_en: 'DOCX Skill',
      desc_en: 'AI-powered professional Word document creation tool with formatting support',
    },
    credentials: null,
    create_time: '2025-11-05 23:48:17',
    update_time: '2025-11-05 23:48:17',
    config_list: null,
  },
  {
    agent_tool_id: 'document_skills_pdf',
    id: 143,
    icon: '/static/image/my-agent-default-avatar.b998d96f.png',
    name: 'PDF Document Tool',
    desc: 'An AI-powered PDF tool for creating, editing, merging, and completing forms.',
    type: 'skills',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {
      tool_name: 'document_skills_pdf',
      tool_description:
        'PDF manipulation toolkit for extracting text and tables, creating new PDFs, merging/splitting documents, and handling forms. This tool works with PDF documents for programmatically processing, generating, analyzing, and filling PDF forms at scale',
    },
    config: null,
    ext: {
      name_en: 'PDF Skill',
      desc_en: 'AI-powered PDF manipulation toolkit for creation, editing and form filling',
    },
    credentials: null,
    create_time: '2025-11-05 23:48:29',
    update_time: '2025-11-05 23:48:29',
    config_list: null,
  },
  {
    agent_tool_id: 'document_skills_xlsx',
    id: 144,
    icon: '/static/image/my-agent-default-avatar.b998d96f.png',
    name: 'Excel Spreadsheet Tool',
    desc: 'An AI-powered spreadsheet tool with formulas, data analysis, and visualization.',
    type: 'skills',
    service_type: null,
    status: 'ACTIVE',
    need_config: false,
    content: {
      tool_name: 'document_skills_xlsx',
      tool_description:
        'Spreadsheet creation, editing, and analysis with support for formulas, formatting, data analysis, and visualization. This tool works with spreadsheets (.xlsx, .xlsm, .csv, .tsv, etc) for: (1) Creating new spreadsheets with formulas and formatting, (2) Reading or analyzing data, (3) Modifying existing spreadsheets while preserving formulas, (4) Data analysis and visualization in spreadsheets, or (5) Recalculating formulas',
    },
    config: null,
    ext: {
      name_en: 'XLSX Skill',
      desc_en: 'AI-powered Excel spreadsheet tool with formulas and data analysis',
    },
    credentials: null,
    create_time: '2025-11-05 23:48:39',
    update_time: '2025-11-05 23:48:39',
    config_list: null,
  },
];
