name: lint

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "From which folder this pipeline executes"

permissions:
  contents: read

env:
  RUFF_OUTPUT_FORMAT: github

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
    name: "lint #${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: Ana06/get-changed-files@v2.3.0
        with:
          filter: "${{ inputs.working-directory }}/**"
      - name: Set up Python ${{ matrix.python-version }}
        if: steps.changed-files.outputs.all
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-suffix: lint-${{ inputs.working-directory }}

      - name: Install dependencies
        if: steps.changed-files.outputs.all
        working-directory: ${{ inputs.working-directory }}
        run: uv sync --all-extras --group dev

      - name: Analysing package code with our lint
        if: steps.changed-files.outputs.all
        working-directory: ${{ inputs.working-directory }}
        run: uv run ruff check --fix . && uv run ruff format


